import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static const String _languageKey = 'selected_language';
  
  static Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'tr';
  }
  
  static Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
  }
}

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Motivasyonunu Takip Et',
      'welcome_morning': 'Günaydın!',
      'welcome_afternoon': 'İyi Günler!',
      'welcome_evening': 'İyi akşamlar!',
      'welcome_message': 'Bugün hangi hedeflerini gerçekleştireceksin?',
      'today_summary': 'Bugünün Özeti',
      'this_week': 'Bu Hafta',
      'completed': 'Tamamlanan',
      'remaining': 'Kalan',

      'my_motivations': 'Rutinlerim',
      'quick_actions': 'Hızlı İşlemler',
      'complete_today': 'Bugünü Tamamla',
      'dashboard': 'Anasayfa',
      'motivations': 'Rutinler',
      'motivation': 'Rutin',
      'about': 'Hakkımızda',
      'daily_record': 'Günlük Kayıt',
      'view_details': 'Detayları Gör',
      'statistics_progress': 'İstatistikler ve ilerleme grafikleri',
      'did_you_do_today': 'Bugün bu rutini gerçekleştirdin mi?',
      'language': 'Dil',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'gün',
      'minutes': 'dk',
      'total_days': 'Toplam Gün',
      'total_time': 'Toplam Süre',

      'add_motivation': 'Rutin Ekle',
      'no_motivations': 'Henüz rutin eklemedin',
      'add_first_motivation': 'İlk rutinini eklemek için + butonuna bas',
      'login_welcome': 'Motiv App\'e Hoş Geldin',
      'login_subtitle': 'Motivasyonunu takip etmeye başla',
      'google_signin': 'Google ile Giriş Yap',
      'continue_guest': 'Misafir olarak devam et',
      'completed_routines': 'Tamamlanan Rutinler',
      'no_completed_routines': 'Henüz tamamlanan rutin yok',
      'completed_routines_desc': 'Motivasyonlarınız rutine oturduğunda\nburada görünecek',
      'routine_completed': 'Rutine Oturdu',
      'predefined_routines': 'Hazır Rutinler',
      'custom_motivation': 'Özel Rutin Oluştur',
      'motivation_title': 'Rutin Başlığı',
      'description': 'Açıklama',
      'category': 'Kategori',
      'frequency': 'Sıklık',
      'target_time': 'Hedef Süre (dakika)',
      'reminder': 'Hatırlatma',
      'set_alarm': 'Alarm Kur',
      'alarm_desc': 'Belirlediğin saatte hatırlatma al',
      'select_alarm_time': 'Alarm Saati Seç',
      'notes_optional': 'Notlar (İsteğe Bağlı)',
      'save_motivation': 'Rutini Kaydet',
      'daily': 'Günlük',
      'weekly': 'Haftalık',
      'monthly': 'Aylık',
      'spiritual': 'Manevi',
      'education': 'Eğitim',
      'health': 'Sağlık',
      'personal': 'Kişisel',
      'title_required': 'Başlık gerekli',
      'select_day': 'Lütfen en az bir gün seçin',
      'which_days': 'Hangi Günler?',
      'type_selection': 'Tür Seçimi',
      'how_often': 'Ne Sıklıkla?',
      'target_time_minutes': 'Hedef süre gerekli',
      'app_info': 'Uygulama Bilgileri',
      'version': 'Versiyon 1.0.4',
      'app_description': 'Motivasyonunu takip et, hedeflerine ulaş! Günlük alışkanlıklarını oluştur ve sürdür.',
      'features': 'Özellikler',
      'legal_info': 'Yasal Bilgiler',
      'contact': 'İletişim',
      'copyright': 'Telif Hakları',
      'privacy': 'Gizlilik',
      'terms': 'Kullanım Koşulları',
      'disclaimer': 'Sorumluluk Reddi',
      'all': 'Tümü',
      'no_motivations_found': 'Rutin bulunamadı',
      'household': 'Ev İşleri',
      'self_care': 'Kişisel Bakım',
      'social': 'Sosyal',
      'hobby': 'Hobi',
      'career': 'İş/Kariyer',
      'completed_days': 'Tamamlanan',
      'current_streak': 'Seri',
      'success_rate': 'Başarı Oranı',
      'last_30_days': 'Son 30 Gün',
      'daily_notes': 'Günlük Notlar',
      'add_note': 'Not Ekle',
      'no_notes_yet': 'Henüz not eklenmemiş. İlk notunu eklemek için + butonuna bas.',
      'recent_activities': 'Son Aktiviteler',
      'add_daily_note': 'Günlük Not Ekle',
      'how_was_today': 'Bugün nasıl geçti? Notlarını yaz...',
      'how_do_you_feel': 'Ruh halin nasıl?',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'note_saved': 'Not kaydedildi!',
      'complete_today_title': 'Bugünü Tamamla',
      'did_you_complete': 'Bugün bu motivasyonu tamamladın mı?',
      'how_many_minutes': 'Kaç dakika harcadın?',
      'complete': 'Tamamla',
      'marked_complete': 'Bugün tamamlandı olarak işaretlendi!',
      'today': 'Bugün',
      'yesterday': 'Dün',
      'days_ago': 'gün önce',
      'completed_status': 'Tamamlandı',
      'not_completed': 'Tamamlanmadı',
      'not_completed_status': 'Tamamlanmadı',
      'ok': 'Tamam',
      'delete': 'Sil',
      'motivation_moved_to_completed': 'Rutin tamamlanan rutinlere taşındı!',
      'motivation_deleted': 'Rutin silindi',
      'view': 'Görünüm',
      'mark_all_complete_question': 'Tüm rutinleri bugün için tamamlandı olarak işaretlemek istiyor musun?',
      'all_motivations_completed': 'Tüm rutinler tamamlandı!',
      'create_daily_record': 'Günlük Kayıt Oluştur',
      'dashboard_feature': 'Dashboard',
      'dashboard_desc': 'Rutinlerinin özetini görüntüle',
      'progress_tracking': 'İlerleme Takibi',
      'progress_desc': 'Günlük, haftalık ve aylık istatistikler',
      'daily_notes_feature': 'Günlük Notlar',
      'daily_notes_desc': 'Ruh halin ve deneyimlerini kaydet',
      'reminders': 'Hatırlatmalar',
      'reminders_desc': 'Belirlediğin saatlerde bildirim al',
      'categories_feature': 'Kategoriler',
      'categories_desc': 'Manevi, eğitim, sağlık ve kişisel gelişim',
      'detailed_analysis': 'Detaylı Analiz',
      'analysis_desc': 'Grafikler ve başarı oranları',
      'copyright_title': 'Telif Hakları',
      'copyright_desc': '© 2024 Motiv App. Tüm hakları saklıdır. Bu uygulamanın tüm içeriği, tasarımı ve kodları telif hakkı ile korunmaktadır.',
      'privacy_title': 'Gizlilik',
      'privacy_desc': 'Kişisel verileriniz güvenli bir şekilde saklanır ve üçüncü taraflarla paylaşılmaz. Verileriniz sadece uygulama işlevsellik için kullanılır.',
      'terms_title': 'Kullanım Koşulları',
      'terms_desc': 'Bu uygulamayı kullanarak, belirlenen kullanım koşullarını kabul etmiş olursunuz. Uygulamayı kötüye kullanmak yasaktır.',
      'disclaimer_title': 'Sorumluluk Reddi',
      'disclaimer_desc': 'Uygulama "olduğu gibi" sunulmaktadır. Geliştiriciler, uygulamanın kullanımından doğabilecek herhangi bir zarardan sorumlu değildir.',
      'email': 'E-posta',
      'website': 'Web Sitesi',
      'bug_report': 'Hata Bildirimi',
      'bug_report_desc': 'Bir hata mı buldun? Bize bildir!',
      'rating': 'Değerlendirme',
      'rating_desc': 'Uygulamayı beğendiysen yıldız ver!',
      'feedback_message': 'Geri bildirimleriniz bizim için çok değerli. Uygulamayı geliştirmek için önerilerinizi bekliyoruz.',
      'alarm_time': 'Alarm Saati',
      'daily_tasks': 'Günlük Görevler',
      'no_daily_tasks': 'Henüz günlük görev eklemedin',
      'add_first_task': 'İlk görevini eklemek için + butonuna bas',
      'active_tasks': 'Aktif Görevler',
      'completed_tasks': 'Tamamlanan Görevler',
      'expires': 'Süresi Doluyor',
      'expired': 'Süresi Doldu',
      'mark_complete': 'Tamamlandı Olarak İşaretle',
      'task_completed': 'Görev Tamamlandı',
      'add_to_calendar_question': 'Bu görevi takvime eklemek istiyor musun?',
      'yes': 'Evet',
      'no': 'Hayır',
      'added_to_calendar': 'Takvime eklendi!',
      'task_deleted': 'Görev silindi',
      'add_daily_task': 'Günlük Görev Ekle',
      'task_title': 'Görev Başlığı',
      'expires_in': 'Süresi',
      'hours': 'saat',
      'completed_motivations_today': 'Bugün tamamlanan rutinler:',
      'remaining_motivations_today': 'Bugün kalan rutinler:',
      'target': 'Hedef',
      'more': 'tane daha',
      'no_motivations_added_yet': 'Henüz rutin eklenmemiş',
      'tasks_in_progress': 'Şu anda devam eden görevler',
      'completed_tasks_today': 'Bugün tamamlanan görevler',
      'expired_tasks': 'Süresi geçmiş görevler',
      'no_tasks_in_category': 'Bu kategoride görev bulunamadı',
      'tasks': 'görev',
      'task': 'görev',
      'active': 'Aktif',
      'upcoming_tasks': 'Yaklaşan Görevler',
      'close': 'Kapat',
      'created': 'Oluşturuldu',
      'note': 'Not',
      'add_note_hint': 'Notunuzu buraya yazın...',
      'note_added': 'Not eklendi',
      'complete_task': 'Görevi Tamamla',
      'mark_task_complete_question': 'Bu görevi tamamlandı olarak işaretlemek istiyor musun?',
      'error_occurred': 'Bir hata oluştu',
      'progress_chart': 'İlerleme Grafiği',
      'details': 'Detayları',
      'motivation_notes_hint': 'Bu rutin hakkında notların...',
      'yes_did_it': 'Evet, Yaptım',
      'no_could_not': 'Hayır, Yapamadım',
      'example': 'Örnek',
      'how_do_you_feel_today': 'Bu rutin için bugün ruh halin nasıl?',
      'complete_record': 'Kaydı Tamamla',
      'daily_record_completed': 'için günlük kayıt tamamlandı!',
      'record_saved_try_tomorrow': 'Kayıt alındı. Yarın tekrar dene!',
      'mood_bad': 'Kötü',
      'mood_difficult': 'Zor',
      'mood_normal': 'Normal',
      'mood_good': 'İyi',
      'mood_great': 'Harika',
      'password': 'Şifre',
      'email_required': 'E-posta gerekli',
      'email_invalid': 'Geçersiz e-posta',
      'password_required': 'Şifre gerekli',
      'password_min_length': 'Şifre en az 6 karakter olmalı',
      'remember_me': 'Beni Hatırla',
      'sign_up': 'Kayıt Ol',
      'sign_in': 'Giriş Yap',
      'already_have_account': 'Zaten hesabın var mı? Giriş yap',
      'dont_have_account': 'Hesabın yok mu? Kayıt ol',
      'or': 'veya',
      'check_email_verification': 'E-postanı kontrol et ve doğrulama linkine tıkla',
      'account': 'Hesap',
      'profile_info': 'Profil Bilgileri',
      'full_name': 'Ad Soyad',
      'age': 'Yaş',
      'country': 'Ülke',
      'city': 'Şehir',
      'no_name': 'Ad Girilmemiş',
      'name_required': 'Ad soyad gerekli',
      'age_invalid': 'Geçersiz yaş (1-120 arası)',
      'profile_updated': 'Profil güncellendi',
      'sign_out': 'Çıkış Yap',
      'sign_out_confirm': 'Hesaptan çıkış yapmak istediğinizden emin misiniz?',
      'profile_setup': 'Profil Kurulumu',
      'complete_profile': 'Profilini Tamamla',
      'profile_subtitle': 'Seni daha iyi tanımak için birkaç bilgi alalım',
      'age_required': 'Yaş gerekli',
      'country_required': 'Ülke seçimi gerekli',
      'city_required': 'Şehir seçimi gerekli',
      'complete_setup': 'Kurulumu Tamamla'
    },
    'en': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Track Your Motivation',
      'welcome_morning': 'Good Morning!',
      'welcome_afternoon': 'Good Afternoon!',
      'welcome_evening': 'Good Evening!',
      'welcome_message': 'Which goals will you achieve today?',
      'today_summary': 'Today\'s Summary',
      'this_week': 'This Week',
      'completed': 'Completed',
      'remaining': 'Remaining',

      'my_motivations': 'My Routines',
      'quick_actions': 'Quick Actions',
      'complete_today': 'Complete Today',
      'dashboard': 'Home',
      'motivations': 'Routines',
      'motivation': 'Routine',
      'about': 'About',
      'daily_record': 'Daily Record',
      'view_details': 'View Details',
      'statistics_progress': 'Statistics and progress charts',
      'did_you_do_today': 'Did you accomplish this routine today?',
      'language': 'Language',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'days',
      'minutes': 'min',
      'total_days': 'Total Days',
      'total_time': 'Total Time',

      'add_motivation': 'Add Routine',
      'no_motivations': 'No routines added yet',
      'add_first_motivation': 'Tap + button to add your first routine',
      'login_welcome': 'Welcome to Motiv App',
      'login_subtitle': 'Start tracking your motivation',
      'google_signin': 'Sign in with Google',
      'continue_guest': 'Continue as guest',
      'completed_routines': 'Completed Routines',
      'no_completed_routines': 'No completed routines yet',
      'completed_routines_desc': 'When your motivations become routine\nthey will appear here',
      'routine_completed': 'Became Routine',
      'predefined_routines': 'Ready Routines',
      'custom_motivation': 'Create Custom Routine',
      'motivation_title': 'Routine Title',
      'description': 'Description',
      'category': 'Category',
      'frequency': 'Frequency',
      'target_time': 'Target Time (minutes)',
      'reminder': 'Reminder',
      'set_alarm': 'Set Alarm',
      'alarm_desc': 'Get reminder at your set time',
      'select_alarm_time': 'Select Alarm Time',
      'notes_optional': 'Notes (Optional)',
      'save_motivation': 'Save Routine',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'spiritual': 'Spiritual',
      'education': 'Education',
      'health': 'Health',
      'personal': 'Personal',
      'title_required': 'Title is required',
      'select_day': 'Please select at least one day',
      'which_days': 'Which Days?',
      'type_selection': 'Type Selection',
      'how_often': 'How Often?',
      'target_time_minutes': 'Target time is required',
      'app_info': 'App Information',
      'version': 'Version 1.0.4',
      'app_description': 'Track your motivation, reach your goals! Create and maintain your daily habits.',
      'features': 'Features',
      'legal_info': 'Legal Information',
      'contact': 'Contact',
      'copyright': 'Copyright',
      'privacy': 'Privacy',
      'terms': 'Terms of Use',
      'disclaimer': 'Disclaimer',
      'all': 'All',
      'no_motivations_found': 'No routines found',
      'household': 'Household',
      'self_care': 'Self Care',
      'social': 'Social',
      'hobby': 'Hobby',
      'career': 'Career',
      'completed_days': 'Completed',
      'current_streak': 'Streak',
      'success_rate': 'Success Rate',
      'last_30_days': 'Last 30 Days',
      'daily_notes': 'Daily Notes',
      'add_note': 'Add Note',
      'no_notes_yet': 'No notes added yet. Tap + button to add your first note.',
      'recent_activities': 'Recent Activities',
      'add_daily_note': 'Add Daily Note',
      'how_was_today': 'How was today? Write your notes...',
      'how_do_you_feel': 'How do you feel?',
      'cancel': 'Cancel',
      'save': 'Save',
      'note_saved': 'Note saved!',
      'complete_today_title': 'Complete Today',
      'did_you_complete': 'Did you complete this motivation today?',
      'how_many_minutes': 'How many minutes did you spend?',
      'complete': 'Complete',
      'marked_complete': 'Marked as completed for today!',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'completed_status': 'Completed',
      'not_completed': 'Not Completed',
      'not_completed_status': 'Not Completed',
      'ok': 'OK',
      'delete': 'Delete',
      'motivation_moved_to_completed': 'Routine moved to completed routines!',
      'motivation_deleted': 'Routine deleted',
      'view': 'View',
      'mark_all_complete_question': 'Do you want to mark all routines as completed for today?',
      'all_motivations_completed': 'All routines completed!',
      'create_daily_record': 'Create Daily Record',
      'dashboard_feature': 'Dashboard',
      'dashboard_desc': 'View summary of your routines',
      'progress_tracking': 'Progress Tracking',
      'progress_desc': 'Daily, weekly and monthly statistics',
      'daily_notes_feature': 'Daily Notes',
      'daily_notes_desc': 'Record your mood and experiences',
      'reminders': 'Reminders',
      'reminders_desc': 'Get notifications at your set times',
      'categories_feature': 'Categories',
      'categories_desc': 'Spiritual, education, health and personal development',
      'detailed_analysis': 'Detailed Analysis',
      'analysis_desc': 'Charts and success rates',
      'copyright_title': 'Copyright',
      'copyright_desc': '© 2024 Motiv App. All rights reserved. All content, design and code of this application are protected by copyright.',
      'privacy_title': 'Privacy',
      'privacy_desc': 'Your personal data is stored securely and not shared with third parties. Your data is only used for app functionality.',
      'terms_title': 'Terms of Use',
      'terms_desc': 'By using this application, you agree to the specified terms of use. Misuse of the application is prohibited.',
      'disclaimer_title': 'Disclaimer',
      'disclaimer_desc': 'The application is provided "as is". Developers are not responsible for any damage that may arise from the use of the application.',
      'email': 'Email',
      'website': 'Website',
      'bug_report': 'Bug Report',
      'bug_report_desc': 'Found a bug? Let us know!',
      'rating': 'Rating',
      'rating_desc': 'If you liked the app, give us stars!',
      'feedback_message': 'Your feedback is very valuable to us. We look forward to your suggestions to improve the app.',
      'alarm_time': 'Alarm Time',
      'daily_tasks': 'Daily Tasks',
      'no_daily_tasks': 'No daily tasks added yet',
      'add_first_task': 'Tap + button to add your first task',
      'active_tasks': 'Active Tasks',
      'completed_tasks': 'Completed Tasks',
      'expires': 'Expires',
      'expired': 'Expired',
      'mark_complete': 'Mark as Complete',
      'task_completed': 'Task Completed',
      'add_to_calendar_question': 'Do you want to add this task to calendar?',
      'yes': 'Yes',
      'no': 'No',
      'added_to_calendar': 'Added to calendar!',
      'task_deleted': 'Task deleted',
      'add_daily_task': 'Add Daily Task',
      'task_title': 'Task Title',
      'expires_in': 'Expires in',
      'hours': 'hours',
      'completed_motivations_today': 'Completed routines today:',
      'remaining_motivations_today': 'Remaining routines today:',
      'target': 'Target',
      'more': 'more',
      'no_motivations_added_yet': 'No routines added yet',
      'tasks_in_progress': 'Tasks currently in progress',
      'completed_tasks_today': 'Tasks completed today',
      'expired_tasks': 'Expired tasks',
      'no_tasks_in_category': 'No tasks found in this category',
      'tasks': 'tasks',
      'task': 'task',
      'active': 'Active',
      'upcoming_tasks': 'Upcoming Tasks',
      'close': 'Close',
      'created': 'Created',
      'note': 'Note',
      'add_note_hint': 'Write your note here...',
      'note_added': 'Note added',
      'complete_task': 'Complete Task',
      'mark_task_complete_question': 'Do you want to mark this task as completed?',
      'error_occurred': 'An error occurred',
      'progress_chart': 'Progress Chart',
      'details': 'Details',
      'motivation_notes_hint': 'Your notes about this routine...',
      'yes_did_it': 'Yes, I Did It',
      'no_could_not': 'No, I Could Not',
      'example': 'Example',
      'how_do_you_feel_today': 'How do you feel about this routine today?',
      'complete_record': 'Complete Record',
      'daily_record_completed': 'daily record completed!',
      'record_saved_try_tomorrow': 'Record saved. Try again tomorrow!',
      'mood_bad': 'Bad',
      'mood_difficult': 'Difficult',
      'mood_normal': 'Normal',
      'mood_good': 'Good',
      'mood_great': 'Great',
      'password': 'Password',
      'email_required': 'Email is required',
      'email_invalid': 'Invalid email',
      'password_required': 'Password is required',
      'password_min_length': 'Password must be at least 6 characters',
      'remember_me': 'Remember Me',
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'already_have_account': 'Already have an account? Sign in',
      'dont_have_account': 'Don\'t have an account? Sign up',
      'or': 'or',
      'check_email_verification': 'Check your email and click the verification link',
      'account': 'Account',
      'profile_info': 'Profile Information',
      'full_name': 'Full Name',
      'age': 'Age',
      'country': 'Country',
      'city': 'City',
      'no_name': 'No Name Entered',
      'name_required': 'Full name is required',
      'age_invalid': 'Invalid age (1-120)',
      'profile_updated': 'Profile updated',
      'sign_out': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'profile_setup': 'Profile Setup',
      'complete_profile': 'Complete Your Profile',
      'profile_subtitle': 'Let us get to know you better with some information',
      'age_required': 'Age is required',
      'country_required': 'Country selection is required',
      'city_required': 'City selection is required',
      'complete_setup': 'Complete Setup'
    },
    'de': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Verfolge deine Motivation',
      'welcome_morning': 'Guten Morgen!',
      'welcome_afternoon': 'Guten Tag!',
      'welcome_evening': 'Guten Abend!',
      'welcome_message': 'Welche Ziele wirst du heute erreichen?',
      'today_summary': 'Heutige Zusammenfassung',
      'this_week': 'Diese Woche',
      'completed': 'Abgeschlossen',
      'remaining': 'Verbleibend',
      'my_motivations': 'Meine Routinen',
      'quick_actions': 'Schnellaktionen',
      'complete_today': 'Heute abschließen',
      'dashboard': 'Startseite',
      'motivations': 'Routinen',
      'motivation': 'Routine',
      'about': 'Über',
      'daily_record': 'Täglicher Eintrag',
      'view_details': 'Details anzeigen',
      'statistics_progress': 'Statistiken und Fortschrittsdiagramme',
      'did_you_do_today': 'Hast du diese Routine heute durchgeführt?',
      'language': 'Sprache',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'Tage',
      'minutes': 'Min',
      'total_days': 'Gesamttage',
      'total_time': 'Gesamtzeit',
      'add_motivation': 'Routine hinzufügen',
      'no_motivations': 'Noch keine Routinen hinzugefügt',
      'add_first_motivation': 'Tippe auf + um deine erste Routine hinzuzufügen',
      'login_welcome': 'Willkommen bei Motiv App',
      'login_subtitle': 'Beginne deine Motivation zu verfolgen',
      'google_signin': 'Mit Google anmelden',
      'continue_guest': 'Als Gast fortfahren',
      'completed_routines': 'Abgeschlossene Routinen',
      'no_completed_routines': 'Noch keine abgeschlossenen Routinen',
      'completed_routines_desc': 'Wenn deine Motivationen zur Routine werden\nerscheinen sie hier',
      'routine_completed': 'Zur Routine geworden',
      'predefined_routines': 'Vorgefertigte Routinen',
      'custom_motivation': 'Eigene Routine erstellen',
      'motivation_title': 'Routinetitel',
      'description': 'Beschreibung',
      'category': 'Kategorie',
      'frequency': 'Häufigkeit',
      'target_time': 'Zielzeit (Minuten)',
      'reminder': 'Erinnerung',
      'set_alarm': 'Alarm einstellen',
      'alarm_desc': 'Erhalte Erinnerung zur eingestellten Zeit',
      'select_alarm_time': 'Alarmzeit auswählen',
      'notes_optional': 'Notizen (Optional)',
      'save_motivation': 'Routine speichern',
      'daily': 'Täglich',
      'weekly': 'Wöchentlich',
      'monthly': 'Monatlich',
      'spiritual': 'Spirituell',
      'education': 'Bildung',
      'health': 'Gesundheit',
      'personal': 'Persönlich',
      'title_required': 'Titel erforderlich',
      'select_day': 'Bitte wähle mindestens einen Tag',
      'which_days': 'Welche Tage?',
      'type_selection': 'Typauswahl',
      'how_often': 'Wie oft?',
      'target_time_minutes': 'Zielzeit erforderlich',
      'app_info': 'App-Informationen',
      'version': 'Version 1.0.4',
      'app_description': 'Verfolge deine Motivation, erreiche deine Ziele! Erstelle und pflege deine täglichen Gewohnheiten.',
      'features': 'Funktionen',
      'legal_info': 'Rechtliche Informationen',
      'contact': 'Kontakt',
      'copyright': 'Urheberrecht',
      'privacy': 'Datenschutz',
      'terms': 'Nutzungsbedingungen',
      'disclaimer': 'Haftungsausschluss',
      'all': 'Alle',
      'no_motivations_found': 'Keine Routinen gefunden',
      'household': 'Haushalt',
      'self_care': 'Selbstfürsorge',
      'social': 'Sozial',
      'hobby': 'Hobby',
      'career': 'Karriere',
      'completed_days': 'Abgeschlossen',
      'current_streak': 'Serie',
      'success_rate': 'Erfolgsquote',
      'last_30_days': 'Letzte 30 Tage',
      'daily_notes': 'Tägliche Notizen',
      'add_note': 'Notiz hinzufügen',
      'no_notes_yet': 'Noch keine Notizen. Tippe auf + um deine erste Notiz hinzuzufügen.',
      'recent_activities': 'Letzte Aktivitäten',
      'add_daily_note': 'Tägliche Notiz hinzufügen',
      'how_was_today': 'Wie war heute? Schreibe deine Notizen...',
      'how_do_you_feel': 'Wie fühlst du dich?',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'note_saved': 'Notiz gespeichert!',
      'complete_today_title': 'Heute abschließen',
      'did_you_complete': 'Hast du diese Motivation heute abgeschlossen?',
      'how_many_minutes': 'Wie viele Minuten hast du verbracht?',
      'complete': 'Abschließen',
      'marked_complete': 'Als abgeschlossen für heute markiert!',
      'today': 'Heute',
      'yesterday': 'Gestern',
      'days_ago': 'Tage her',
      'completed_status': 'Abgeschlossen',
      'not_completed': 'Nicht abgeschlossen',
      'not_completed_status': 'Nicht abgeschlossen',
      'ok': 'OK',
      'delete': 'Löschen',
      'motivation_moved_to_completed': 'Routine zu abgeschlossenen Routinen verschoben!',
      'motivation_deleted': 'Routine gelöscht',
      'view': 'Ansicht',
      'mark_all_complete_question': 'Möchtest du alle Routinen für heute als abgeschlossen markieren?',
      'all_motivations_completed': 'Alle Routinen abgeschlossen!',
      'create_daily_record': 'Täglichen Eintrag erstellen',
      'dashboard_feature': 'Dashboard',
      'dashboard_desc': 'Zusammenfassung deiner Routinen anzeigen',
      'progress_tracking': 'Fortschrittsverfolgung',
      'progress_desc': 'Tägliche, wöchentliche und monatliche Statistiken',
      'daily_notes_feature': 'Tägliche Notizen',
      'daily_notes_desc': 'Zeichne deine Stimmung und Erfahrungen auf',
      'reminders': 'Erinnerungen',
      'reminders_desc': 'Erhalte Benachrichtigungen zu deinen eingestellten Zeiten',
      'categories_feature': 'Kategorien',
      'categories_desc': 'Spirituell, Bildung, Gesundheit und persönliche Entwicklung',
      'detailed_analysis': 'Detaillierte Analyse',
      'analysis_desc': 'Diagramme und Erfolgsquoten',
      'copyright_title': 'Urheberrecht',
      'copyright_desc': '© 2024 Motiv App. Alle Rechte vorbehalten.',
      'privacy_title': 'Datenschutz',
      'privacy_desc': 'Deine persönlichen Daten werden sicher gespeichert und nicht mit Dritten geteilt.',
      'terms_title': 'Nutzungsbedingungen',
      'terms_desc': 'Durch die Nutzung dieser App stimmst du den Nutzungsbedingungen zu.',
      'disclaimer_title': 'Haftungsausschluss',
      'disclaimer_desc': 'Die App wird "wie besehen" bereitgestellt.',
      'email': 'E-Mail',
      'website': 'Webseite',
      'bug_report': 'Fehlerbericht',
      'bug_report_desc': 'Fehler gefunden? Lass es uns wissen!',
      'rating': 'Bewertung',
      'rating_desc': 'Wenn dir die App gefällt, gib uns Sterne!',
      'feedback_message': 'Dein Feedback ist uns sehr wichtig.',
      'alarm_time': 'Alarmzeit',
      'daily_tasks': 'Tägliche Aufgaben',
      'no_daily_tasks': 'Noch keine täglichen Aufgaben',
      'add_first_task': 'Tippe auf + um deine erste Aufgabe hinzuzufügen',
      'active_tasks': 'Aktive Aufgaben',
      'completed_tasks': 'Abgeschlossene Aufgaben',
      'expires': 'Läuft ab',
      'expired': 'Abgelaufen',
      'mark_complete': 'Als abgeschlossen markieren',
      'task_completed': 'Aufgabe abgeschlossen',
      'add_to_calendar_question': 'Möchtest du diese Aufgabe zum Kalender hinzufügen?',
      'yes': 'Ja',
      'no': 'Nein',
      'added_to_calendar': 'Zum Kalender hinzugefügt!',
      'task_deleted': 'Aufgabe gelöscht',
      'add_daily_task': 'Tägliche Aufgabe hinzufügen',
      'task_title': 'Aufgabentitel',
      'expires_in': 'Läuft ab in',
      'hours': 'Stunden',
      'completed_motivations_today': 'Heute abgeschlossene Routinen:',
      'remaining_motivations_today': 'Heute verbleibende Routinen:',
      'target': 'Ziel',
      'more': 'mehr',
      'no_motivations_added_yet': 'Noch keine Routinen hinzugefügt',
      'tasks_in_progress': 'Laufende Aufgaben',
      'completed_tasks_today': 'Heute abgeschlossene Aufgaben',
      'expired_tasks': 'Abgelaufene Aufgaben',
      'no_tasks_in_category': 'Keine Aufgaben in dieser Kategorie',
      'tasks': 'Aufgaben',
      'task': 'Aufgabe',
      'active': 'Aktiv',
      'upcoming_tasks': 'Bevorstehende Aufgaben',
      'close': 'Schließen',
      'created': 'Erstellt',
      'note': 'Notiz',
      'add_note_hint': 'Schreibe deine Notiz hier...',
      'note_added': 'Notiz hinzugefügt',
      'complete_task': 'Aufgabe abschließen',
      'mark_task_complete_question': 'Möchtest du diese Aufgabe als abgeschlossen markieren?',
      'error_occurred': 'Ein Fehler ist aufgetreten',
      'progress_chart': 'Fortschrittsdiagramm',
      'details': 'Details',
      'motivation_notes_hint': 'Deine Notizen zu dieser Routine...',
      'yes_did_it': 'Ja, habe ich',
      'no_could_not': 'Nein, konnte nicht',
      'example': 'Beispiel',
      'how_do_you_feel_today': 'Wie fühlst du dich heute bei dieser Routine?',
      'complete_record': 'Eintrag abschließen',
      'daily_record_completed': 'täglicher Eintrag abgeschlossen!',
      'record_saved_try_tomorrow': 'Eintrag gespeichert. Versuche es morgen erneut!',
      'mood_bad': 'Schlecht',
      'mood_difficult': 'Schwierig',
      'mood_normal': 'Normal',
      'mood_good': 'Gut',
      'mood_great': 'Großartig',
      'password': 'Passwort',
      'email_required': 'E-Mail erforderlich',
      'email_invalid': 'Ungültige E-Mail',
      'password_required': 'Passwort erforderlich',
      'password_min_length': 'Passwort muss mindestens 6 Zeichen lang sein',
      'remember_me': 'Angemeldet bleiben',
      'sign_up': 'Registrieren',
      'sign_in': 'Anmelden',
      'already_have_account': 'Hast du bereits ein Konto? Anmelden',
      'dont_have_account': 'Noch kein Konto? Registrieren',
      'or': 'oder',
      'check_email_verification': 'Überprüfe deine E-Mail und klicke auf den Bestätigungslink',
      'account': 'Konto',
      'profile_info': 'Profilinformationen',
      'full_name': 'Vollständiger Name',
      'age': 'Alter',
      'country': 'Land',
      'city': 'Stadt',
      'no_name': 'Kein Name eingegeben',
      'name_required': 'Vollständiger Name erforderlich',
      'age_invalid': 'Ungültiges Alter (1-120)',
      'profile_updated': 'Profil aktualisiert',
      'sign_out': 'Abmelden',
      'sign_out_confirm': 'Bist du sicher, dass du dich abmelden möchtest?',
      'profile_setup': 'Profil-Einrichtung',
      'complete_profile': 'Vervollständige dein Profil',
      'profile_subtitle': 'Lass uns dich besser kennenlernen',
      'age_required': 'Alter erforderlich',
      'country_required': 'Länderauswahl erforderlich',
      'city_required': 'Stadtauswahl erforderlich',
      'complete_setup': 'Einrichtung abschließen'
    },
    'fr': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Suivez votre motivation',
      'welcome_morning': 'Bonjour!',
      'welcome_afternoon': 'Bon après-midi!',
      'welcome_evening': 'Bonsoir!',
      'welcome_message': 'Quels objectifs allez-vous atteindre aujourd\'hui?',
      'today_summary': 'Résumé d\'aujourd\'hui',
      'this_week': 'Cette semaine',
      'completed': 'Terminé',
      'remaining': 'Restant',
      'my_motivations': 'Mes routines',
      'quick_actions': 'Actions rapides',
      'complete_today': 'Terminer aujourd\'hui',
      'dashboard': 'Accueil',
      'motivations': 'Routines',
      'motivation': 'Routine',
      'about': 'À propos',
      'daily_record': 'Enregistrement quotidien',
      'view_details': 'Voir les détails',
      'statistics_progress': 'Statistiques et graphiques de progression',
      'did_you_do_today': 'Avez-vous accompli cette routine aujourd\'hui?',
      'language': 'Langue',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'jours',
      'minutes': 'min',
      'total_days': 'Jours totaux',
      'total_time': 'Temps total',
      'add_motivation': 'Ajouter une routine',
      'no_motivations': 'Aucune routine ajoutée',
      'add_first_motivation': 'Appuyez sur + pour ajouter votre première routine',
      'login_welcome': 'Bienvenue sur Motiv App',
      'login_subtitle': 'Commencez à suivre votre motivation',
      'google_signin': 'Se connecter avec Google',
      'continue_guest': 'Continuer en tant qu\'invité',
      'completed_routines': 'Routines terminées',
      'no_completed_routines': 'Aucune routine terminée',
      'completed_routines_desc': 'Lorsque vos motivations deviennent des routines\nelles apparaîtront ici',
      'routine_completed': 'Devenu routine',
      'predefined_routines': 'Routines prédéfinies',
      'custom_motivation': 'Créer une routine personnalisée',
      'motivation_title': 'Titre de la routine',
      'description': 'Description',
      'category': 'Catégorie',
      'frequency': 'Fréquence',
      'target_time': 'Temps cible (minutes)',
      'reminder': 'Rappel',
      'set_alarm': 'Définir une alarme',
      'alarm_desc': 'Recevez un rappel à l\'heure définie',
      'select_alarm_time': 'Sélectionner l\'heure de l\'alarme',
      'notes_optional': 'Notes (Optionnel)',
      'save_motivation': 'Enregistrer la routine',
      'daily': 'Quotidien',
      'weekly': 'Hebdomadaire',
      'monthly': 'Mensuel',
      'spiritual': 'Spirituel',
      'education': 'Éducation',
      'health': 'Santé',
      'personal': 'Personnel',
      'title_required': 'Titre requis',
      'select_day': 'Veuillez sélectionner au moins un jour',
      'which_days': 'Quels jours?',
      'type_selection': 'Sélection du type',
      'how_often': 'À quelle fréquence?',
      'target_time_minutes': 'Temps cible requis',
      'app_info': 'Informations sur l\'application',
      'version': 'Version 1.0.4',
      'app_description': 'Suivez votre motivation, atteignez vos objectifs! Créez et maintenez vos habitudes quotidiennes.',
      'features': 'Fonctionnalités',
      'legal_info': 'Informations légales',
      'contact': 'Contact',
      'copyright': 'Droits d\'auteur',
      'privacy': 'Confidentialité',
      'terms': 'Conditions d\'utilisation',
      'disclaimer': 'Avertissement',
      'all': 'Tous',
      'no_motivations_found': 'Aucune routine trouvée',
      'household': 'Ménage',
      'self_care': 'Soins personnels',
      'social': 'Social',
      'hobby': 'Loisir',
      'career': 'Carrière',
      'completed_days': 'Terminé',
      'current_streak': 'Série',
      'success_rate': 'Taux de réussite',
      'last_30_days': '30 derniers jours',
      'daily_notes': 'Notes quotidiennes',
      'add_note': 'Ajouter une note',
      'no_notes_yet': 'Aucune note. Appuyez sur + pour ajouter votre première note.',
      'recent_activities': 'Activités récentes',
      'add_daily_note': 'Ajouter une note quotidienne',
      'how_was_today': 'Comment s\'est passée la journée? Écrivez vos notes...',
      'how_do_you_feel': 'Comment vous sentez-vous?',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'note_saved': 'Note enregistrée!',
      'complete_today_title': 'Terminer aujourd\'hui',
      'did_you_complete': 'Avez-vous terminé cette motivation aujourd\'hui?',
      'how_many_minutes': 'Combien de minutes avez-vous passé?',
      'complete': 'Terminer',
      'marked_complete': 'Marqué comme terminé pour aujourd\'hui!',
      'today': 'Aujourd\'hui',
      'yesterday': 'Hier',
      'days_ago': 'jours',
      'completed_status': 'Terminé',
      'not_completed': 'Non terminé',
      'not_completed_status': 'Non terminé',
      'ok': 'OK',
      'delete': 'Supprimer',
      'motivation_moved_to_completed': 'Routine déplacée vers les routines terminées!',
      'motivation_deleted': 'Routine supprimée',
      'view': 'Vue',
      'mark_all_complete_question': 'Voulez-vous marquer toutes les routines comme terminées pour aujourd\'hui?',
      'all_motivations_completed': 'Toutes les routines terminées!',
      'create_daily_record': 'Créer un enregistrement quotidien',
      'dashboard_feature': 'Tableau de bord',
      'dashboard_desc': 'Voir le résumé de vos routines',
      'progress_tracking': 'Suivi des progrès',
      'progress_desc': 'Statistiques quotidiennes, hebdomadaires et mensuelles',
      'daily_notes_feature': 'Notes quotidiennes',
      'daily_notes_desc': 'Enregistrez votre humeur et vos expériences',
      'reminders': 'Rappels',
      'reminders_desc': 'Recevez des notifications aux heures définies',
      'categories_feature': 'Catégories',
      'categories_desc': 'Spirituel, éducation, santé et développement personnel',
      'detailed_analysis': 'Analyse détaillée',
      'analysis_desc': 'Graphiques et taux de réussite',
      'copyright_title': 'Droits d\'auteur',
      'copyright_desc': '© 2024 Motiv App. Tous droits réservés.',
      'privacy_title': 'Confidentialité',
      'privacy_desc': 'Vos données personnelles sont stockées en toute sécurité.',
      'terms_title': 'Conditions d\'utilisation',
      'terms_desc': 'En utilisant cette application, vous acceptez les conditions d\'utilisation.',
      'disclaimer_title': 'Avertissement',
      'disclaimer_desc': 'L\'application est fournie "telle quelle".',
      'email': 'E-mail',
      'website': 'Site web',
      'bug_report': 'Signaler un bug',
      'bug_report_desc': 'Vous avez trouvé un bug? Faites-le nous savoir!',
      'rating': 'Évaluation',
      'rating_desc': 'Si vous aimez l\'application, donnez-nous des étoiles!',
      'feedback_message': 'Vos commentaires sont très précieux pour nous.',
      'alarm_time': 'Heure de l\'alarme',
      'daily_tasks': 'Tâches quotidiennes',
      'no_daily_tasks': 'Aucune tâche quotidienne',
      'add_first_task': 'Appuyez sur + pour ajouter votre première tâche',
      'active_tasks': 'Tâches actives',
      'completed_tasks': 'Tâches terminées',
      'expires': 'Expire',
      'expired': 'Expiré',
      'mark_complete': 'Marquer comme terminé',
      'task_completed': 'Tâche terminée',
      'add_to_calendar_question': 'Voulez-vous ajouter cette tâche au calendrier?',
      'yes': 'Oui',
      'no': 'Non',
      'added_to_calendar': 'Ajouté au calendrier!',
      'task_deleted': 'Tâche supprimée',
      'add_daily_task': 'Ajouter une tâche quotidienne',
      'task_title': 'Titre de la tâche',
      'expires_in': 'Expire dans',
      'hours': 'heures',
      'completed_motivations_today': 'Routines terminées aujourd\'hui:',
      'remaining_motivations_today': 'Routines restantes aujourd\'hui:',
      'target': 'Objectif',
      'more': 'plus',
      'no_motivations_added_yet': 'Aucune routine ajoutée',
      'tasks_in_progress': 'Tâches en cours',
      'completed_tasks_today': 'Tâches terminées aujourd\'hui',
      'expired_tasks': 'Tâches expirées',
      'no_tasks_in_category': 'Aucune tâche dans cette catégorie',
      'tasks': 'tâches',
      'task': 'tâche',
      'active': 'Actif',
      'upcoming_tasks': 'Tâches à venir',
      'close': 'Fermer',
      'created': 'Créé',
      'note': 'Note',
      'add_note_hint': 'Écrivez votre note ici...',
      'note_added': 'Note ajoutée',
      'complete_task': 'Terminer la tâche',
      'mark_task_complete_question': 'Voulez-vous marquer cette tâche comme terminée?',
      'error_occurred': 'Une erreur s\'est produite',
      'progress_chart': 'Graphique de progression',
      'details': 'Détails',
      'motivation_notes_hint': 'Vos notes sur cette routine...',
      'yes_did_it': 'Oui, je l\'ai fait',
      'no_could_not': 'Non, je n\'ai pas pu',
      'example': 'Exemple',
      'how_do_you_feel_today': 'Comment vous sentez-vous aujourd\'hui pour cette routine?',
      'complete_record': 'Terminer l\'enregistrement',
      'daily_record_completed': 'enregistrement quotidien terminé!',
      'record_saved_try_tomorrow': 'Enregistrement sauvegardé. Réessayez demain!',
      'mood_bad': 'Mauvais',
      'mood_difficult': 'Difficile',
      'mood_normal': 'Normal',
      'mood_good': 'Bien',
      'mood_great': 'Excellent',
      'password': 'Mot de passe',
      'email_required': 'E-mail requis',
      'email_invalid': 'E-mail invalide',
      'password_required': 'Mot de passe requis',
      'password_min_length': 'Le mot de passe doit contenir au moins 6 caractères',
      'remember_me': 'Se souvenir de moi',
      'sign_up': 'S\'inscrire',
      'sign_in': 'Se connecter',
      'already_have_account': 'Vous avez déjà un compte? Se connecter',
      'dont_have_account': 'Pas de compte? S\'inscrire',
      'or': 'ou',
      'check_email_verification': 'Vérifiez votre e-mail et cliquez sur le lien de vérification',
      'account': 'Compte',
      'profile_info': 'Informations du profil',
      'full_name': 'Nom complet',
      'age': 'Âge',
      'country': 'Pays',
      'city': 'Ville',
      'no_name': 'Aucun nom saisi',
      'name_required': 'Nom complet requis',
      'age_invalid': 'Âge invalide (1-120)',
      'profile_updated': 'Profil mis à jour',
      'sign_out': 'Se déconnecter',
      'sign_out_confirm': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'profile_setup': 'Configuration du profil',
      'complete_profile': 'Complétez votre profil',
      'profile_subtitle': 'Faites-nous mieux vous connaître',
      'age_required': 'Âge requis',
      'country_required': 'Sélection du pays requise',
      'city_required': 'Sélection de la ville requise',
      'complete_setup': 'Terminer la configuration'
    },
    'it': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Traccia la tua motivazione',
      'welcome_morning': 'Buongiorno!',
      'welcome_afternoon': 'Buon pomeriggio!',
      'welcome_evening': 'Buonasera!',
      'welcome_message': 'Quali obiettivi raggiungerai oggi?',
      'today_summary': 'Riepilogo di oggi',
      'this_week': 'Questa settimana',
      'completed': 'Completato',
      'remaining': 'Rimanente',
      'my_motivations': 'Le mie routine',
      'quick_actions': 'Azioni rapide',
      'complete_today': 'Completa oggi',
      'dashboard': 'Home',
      'motivations': 'Routine',
      'motivation': 'Routine',
      'about': 'Informazioni',
      'daily_record': 'Registro giornaliero',
      'view_details': 'Vedi dettagli',
      'statistics_progress': 'Statistiche e grafici di progresso',
      'did_you_do_today': 'Hai completato questa routine oggi?',
      'language': 'Lingua',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'giorni',
      'minutes': 'min',
      'total_days': 'Giorni totali',
      'total_time': 'Tempo totale',
      'add_motivation': 'Aggiungi routine',
      'no_motivations': 'Nessuna routine aggiunta',
      'add_first_motivation': 'Tocca + per aggiungere la tua prima routine',
      'login_welcome': 'Benvenuto su Motiv App',
      'login_subtitle': 'Inizia a tracciare la tua motivazione',
      'google_signin': 'Accedi con Google',
      'continue_guest': 'Continua come ospite',
      'completed_routines': 'Routine completate',
      'no_completed_routines': 'Nessuna routine completata',
      'completed_routines_desc': 'Quando le tue motivazioni diventano routine\nappariranno qui',
      'routine_completed': 'Diventata routine',
      'predefined_routines': 'Routine predefinite',
      'custom_motivation': 'Crea routine personalizzata',
      'motivation_title': 'Titolo della routine',
      'description': 'Descrizione',
      'category': 'Categoria',
      'frequency': 'Frequenza',
      'target_time': 'Tempo obiettivo (minuti)',
      'reminder': 'Promemoria',
      'set_alarm': 'Imposta allarme',
      'alarm_desc': 'Ricevi promemoria all\'ora impostata',
      'select_alarm_time': 'Seleziona ora allarme',
      'notes_optional': 'Note (Opzionale)',
      'save_motivation': 'Salva routine',
      'daily': 'Giornaliero',
      'weekly': 'Settimanale',
      'monthly': 'Mensile',
      'spiritual': 'Spirituale',
      'education': 'Istruzione',
      'health': 'Salute',
      'personal': 'Personale',
      'title_required': 'Titolo richiesto',
      'select_day': 'Seleziona almeno un giorno',
      'which_days': 'Quali giorni?',
      'type_selection': 'Selezione tipo',
      'how_often': 'Quanto spesso?',
      'target_time_minutes': 'Tempo obiettivo richiesto',
      'app_info': 'Informazioni app',
      'version': 'Versione 1.0.4',
      'app_description': 'Traccia la tua motivazione, raggiungi i tuoi obiettivi! Crea e mantieni le tue abitudini quotidiane.',
      'features': 'Funzionalità',
      'legal_info': 'Informazioni legali',
      'contact': 'Contatto',
      'copyright': 'Copyright',
      'privacy': 'Privacy',
      'terms': 'Termini di utilizzo',
      'disclaimer': 'Disclaimer',
      'all': 'Tutti',
      'no_motivations_found': 'Nessuna routine trovata',
      'household': 'Casa',
      'self_care': 'Cura di sé',
      'social': 'Sociale',
      'hobby': 'Hobby',
      'career': 'Carriera',
      'completed_days': 'Completato',
      'current_streak': 'Serie',
      'success_rate': 'Tasso di successo',
      'last_30_days': 'Ultimi 30 giorni',
      'daily_notes': 'Note giornaliere',
      'add_note': 'Aggiungi nota',
      'no_notes_yet': 'Nessuna nota. Tocca + per aggiungere la tua prima nota.',
      'recent_activities': 'Attività recenti',
      'add_daily_note': 'Aggiungi nota giornaliera',
      'how_was_today': 'Com\'è andata oggi? Scrivi le tue note...',
      'how_do_you_feel': 'Come ti senti?',
      'cancel': 'Annulla',
      'save': 'Salva',
      'note_saved': 'Nota salvata!',
      'complete_today_title': 'Completa oggi',
      'did_you_complete': 'Hai completato questa motivazione oggi?',
      'how_many_minutes': 'Quanti minuti hai trascorso?',
      'complete': 'Completa',
      'marked_complete': 'Segnato come completato per oggi!',
      'today': 'Oggi',
      'yesterday': 'Ieri',
      'days_ago': 'giorni fa',
      'completed_status': 'Completato',
      'not_completed': 'Non completato',
      'not_completed_status': 'Non completato',
      'ok': 'OK',
      'delete': 'Elimina',
      'motivation_moved_to_completed': 'Routine spostata nelle routine completate!',
      'motivation_deleted': 'Routine eliminata',
      'view': 'Vista',
      'mark_all_complete_question': 'Vuoi segnare tutte le routine come completate per oggi?',
      'all_motivations_completed': 'Tutte le routine completate!',
      'create_daily_record': 'Crea registro giornaliero',
      'dashboard_feature': 'Dashboard',
      'dashboard_desc': 'Visualizza il riepilogo delle tue routine',
      'progress_tracking': 'Tracciamento progressi',
      'progress_desc': 'Statistiche giornaliere, settimanali e mensili',
      'daily_notes_feature': 'Note giornaliere',
      'daily_notes_desc': 'Registra il tuo umore e le tue esperienze',
      'reminders': 'Promemoria',
      'reminders_desc': 'Ricevi notifiche agli orari impostati',
      'categories_feature': 'Categorie',
      'categories_desc': 'Spirituale, istruzione, salute e sviluppo personale',
      'detailed_analysis': 'Analisi dettagliata',
      'analysis_desc': 'Grafici e tassi di successo',
      'copyright_title': 'Copyright',
      'copyright_desc': '© 2024 Motiv App. Tutti i diritti riservati.',
      'privacy_title': 'Privacy',
      'privacy_desc': 'I tuoi dati personali sono archiviati in modo sicuro.',
      'terms_title': 'Termini di utilizzo',
      'terms_desc': 'Utilizzando questa app, accetti i termini di utilizzo.',
      'disclaimer_title': 'Disclaimer',
      'disclaimer_desc': 'L\'app viene fornita "così com\'è".',
      'email': 'Email',
      'website': 'Sito web',
      'bug_report': 'Segnala bug',
      'bug_report_desc': 'Hai trovato un bug? Faccelo sapere!',
      'rating': 'Valutazione',
      'rating_desc': 'Se ti piace l\'app, dacci delle stelle!',
      'feedback_message': 'Il tuo feedback è molto prezioso per noi.',
      'alarm_time': 'Ora allarme',
      'daily_tasks': 'Attività giornaliere',
      'no_daily_tasks': 'Nessuna attività giornaliera',
      'add_first_task': 'Tocca + per aggiungere la tua prima attività',
      'active_tasks': 'Attività attive',
      'completed_tasks': 'Attività completate',
      'expires': 'Scade',
      'expired': 'Scaduto',
      'mark_complete': 'Segna come completato',
      'task_completed': 'Attività completata',
      'add_to_calendar_question': 'Vuoi aggiungere questa attività al calendario?',
      'yes': 'Sì',
      'no': 'No',
      'added_to_calendar': 'Aggiunto al calendario!',
      'task_deleted': 'Attività eliminata',
      'add_daily_task': 'Aggiungi attività giornaliera',
      'task_title': 'Titolo attività',
      'expires_in': 'Scade tra',
      'hours': 'ore',
      'completed_motivations_today': 'Routine completate oggi:',
      'remaining_motivations_today': 'Routine rimanenti oggi:',
      'target': 'Obiettivo',
      'more': 'più',
      'no_motivations_added_yet': 'Nessuna routine aggiunta',
      'tasks_in_progress': 'Attività in corso',
      'completed_tasks_today': 'Attività completate oggi',
      'expired_tasks': 'Attività scadute',
      'no_tasks_in_category': 'Nessuna attività in questa categoria',
      'tasks': 'attività',
      'task': 'attività',
      'active': 'Attivo',
      'upcoming_tasks': 'Attività imminenti',
      'close': 'Chiudi',
      'created': 'Creato',
      'note': 'Nota',
      'add_note_hint': 'Scrivi la tua nota qui...',
      'note_added': 'Nota aggiunta',
      'complete_task': 'Completa attività',
      'mark_task_complete_question': 'Vuoi segnare questa attività come completata?',
      'error_occurred': 'Si è verificato un errore',
      'progress_chart': 'Grafico progressi',
      'details': 'Dettagli',
      'motivation_notes_hint': 'Le tue note su questa routine...',
      'yes_did_it': 'Sì, l\'ho fatto',
      'no_could_not': 'No, non ho potuto',
      'example': 'Esempio',
      'how_do_you_feel_today': 'Come ti senti oggi riguardo a questa routine?',
      'complete_record': 'Completa registro',
      'daily_record_completed': 'registro giornaliero completato!',
      'record_saved_try_tomorrow': 'Registro salvato. Riprova domani!',
      'mood_bad': 'Male',
      'mood_difficult': 'Difficile',
      'mood_normal': 'Normale',
      'mood_good': 'Bene',
      'mood_great': 'Ottimo',
      'password': 'Password',
      'email_required': 'Email richiesta',
      'email_invalid': 'Email non valida',
      'password_required': 'Password richiesta',
      'password_min_length': 'La password deve contenere almeno 6 caratteri',
      'remember_me': 'Ricordami',
      'sign_up': 'Registrati',
      'sign_in': 'Accedi',
      'already_have_account': 'Hai già un account? Accedi',
      'dont_have_account': 'Non hai un account? Registrati',
      'or': 'o',
      'check_email_verification': 'Controlla la tua email e clicca sul link di verifica',
      'account': 'Account',
      'profile_info': 'Informazioni profilo',
      'full_name': 'Nome completo',
      'age': 'Età',
      'country': 'Paese',
      'city': 'Città',
      'no_name': 'Nessun nome inserito',
      'name_required': 'Nome completo richiesto',
      'age_invalid': 'Età non valida (1-120)',
      'profile_updated': 'Profilo aggiornato',
      'sign_out': 'Esci',
      'sign_out_confirm': 'Sei sicuro di voler uscire?',
      'profile_setup': 'Configurazione profilo',
      'complete_profile': 'Completa il tuo profilo',
      'profile_subtitle': 'Facci conoscere meglio',
      'age_required': 'Età richiesta',
      'country_required': 'Selezione paese richiesta',
      'city_required': 'Selezione città richiesta',
      'complete_setup': 'Completa configurazione'
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}