import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static const String _languageKey = 'selected_language';
  
  static Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'tr';
  }
  
  static Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
  }
}

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Motivasyonunu Takip Et',
      'welcome_morning': 'Günaydın!',
      'welcome_afternoon': 'İyi öğleden sonralar!',
      'welcome_evening': 'İyi akşamlar!',
      'welcome_message': 'Bugün hangi hedeflerini gerçekleştireceksin?',
      'today_summary': 'Bugünün Özeti',
      'this_week': 'Bu Hafta',
      'completed': 'Tamamlanan',
      'remaining': 'Kalan',

      'my_motivations': 'Motivasyonlarım',
      'quick_actions': 'Hızlı İşlemler',
      'complete_today': 'Bugünü Tamamla',
      'dashboard': 'Anasayfa',
      'motivations': 'Motivasyonlar',
      'motivation': 'Motivasyon',
      'about': 'Hakkımızda',
      'daily_record': 'Günlük Kayıt',
      'view_details': 'Detayları Gör',
      'statistics_progress': 'İstatistikler ve ilerleme grafikleri',
      'did_you_do_today': 'Bugün bu motivasyonu gerçekleştirdin mi?',
      'language': 'Dil',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'gün',
      'minutes': 'dk',
      'total_days': 'Toplam Gün',
      'total_time': 'Toplam Süre',

      'add_motivation': 'Motivasyon Ekle',
      'no_motivations': 'Henüz motivasyon eklemedin',
      'add_first_motivation': 'İlk motivasyonunu eklemek için + butonuna bas',
      'login_welcome': 'Motiv App\'e Hoş Geldin',
      'login_subtitle': 'Motivasyonunu takip etmeye başla',
      'google_signin': 'Google ile Giriş Yap',
      'continue_guest': 'Misafir olarak devam et',
      'completed_routines': 'Tamamlanan Rutinler',
      'no_completed_routines': 'Henüz tamamlanan rutin yok',
      'completed_routines_desc': 'Motivasyonlarınız rutine oturduğunda\nburada görünecek',
      'routine_completed': 'Rutine Oturdu',
      'predefined_motivations': 'Hazır Motivasyonlar',
      'custom_motivation': 'Özel Motivasyon Oluştur',
      'motivation_title': 'Motivasyon Başlığı',
      'description': 'Açıklama',
      'category': 'Kategori',
      'frequency': 'Sıklık',
      'target_time': 'Hedef Süre (dakika)',
      'reminder': 'Hatırlatma',
      'set_alarm': 'Alarm Kur',
      'alarm_desc': 'Belirlediğin saatte hatırlatma al',
      'select_alarm_time': 'Alarm Saati Seç',
      'notes_optional': 'Notlar (İsteğe Bağlı)',
      'save_motivation': 'Motivasyonu Kaydet',
      'daily': 'Günlük',
      'weekly': 'Haftalık',
      'monthly': 'Aylık',
      'spiritual': 'Manevi',
      'education': 'Eğitim',
      'health': 'Sağlık',
      'personal': 'Kişisel',
      'title_required': 'Başlık gerekli',
      'select_day': 'Lütfen en az bir gün seçin',
      'which_days': 'Hangi Günler?',
      'type_selection': 'Tür Seçimi',
      'how_often': 'Ne Sıklıkla?',
      'target_time_minutes': 'Hedef süre gerekli',
      'app_info': 'Uygulama Bilgileri',
      'version': 'Versiyon 1.0.0',
      'app_description': 'Motivasyonunu takip et, hedeflerine ulaş! Günlük alışkanlıklarını oluştur ve sürdür.',
      'features': 'Özellikler',
      'legal_info': 'Yasal Bilgiler',
      'contact': 'İletişim',
      'copyright': 'Telif Hakları',
      'privacy': 'Gizlilik',
      'terms': 'Kullanım Koşulları',
      'disclaimer': 'Sorumluluk Reddi',
      'all': 'Tümü',
      'no_motivations_found': 'Motivasyon bulunamadı',
      'household': 'Ev İşleri',
      'self_care': 'Kişisel Bakım',
      'social': 'Sosyal',
      'hobby': 'Hobi',
      'career': 'İş/Kariyer',
      'completed_days': 'Tamamlanan',
      'current_streak': 'Seri',
      'success_rate': 'Başarı Oranı',
      'last_30_days': 'Son 30 Gün',
      'daily_notes': 'Günlük Notlar',
      'add_note': 'Not Ekle',
      'no_notes_yet': 'Henüz not eklenmemiş. İlk notunu eklemek için + butonuna bas.',
      'recent_activities': 'Son Aktiviteler',
      'add_daily_note': 'Günlük Not Ekle',
      'how_was_today': 'Bugün nasıl geçti? Notlarını yaz...',
      'how_do_you_feel': 'Ruh halin nasıl?',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'note_saved': 'Not kaydedildi!',
      'complete_today_title': 'Bugünü Tamamla',
      'did_you_complete': 'Bugün bu motivasyonu tamamladın mı?',
      'how_many_minutes': 'Kaç dakika harcadın?',
      'complete': 'Tamamla',
      'marked_complete': 'Bugün tamamlandı olarak işaretlendi!',
      'today': 'Bugün',
      'yesterday': 'Dün',
      'days_ago': 'gün önce',
      'completed_status': 'Tamamlandı',
      'not_completed': 'Tamamlanmadı',
      'not_completed_status': 'Tamamlanmadı',
      'ok': 'Tamam',
      'delete': 'Sil',
      'motivation_moved_to_completed': 'Motivasyon tamamlanan rutinlere taşındı!',
      'motivation_deleted': 'Motivasyon silindi',
      'view': 'Görünüm',
      'mark_all_complete_question': 'Tüm motivasyonları bugün için tamamlandı olarak işaretlemek istiyor musun?',
      'all_motivations_completed': 'Tüm motivasyonlar tamamlandı!',
      'create_daily_record': 'Günlük Kayıt Oluştur',
      'dashboard_feature': 'Dashboard',
      'dashboard_desc': 'Motivasyonlarının özetini görüntüle',
      'progress_tracking': 'İlerleme Takibi',
      'progress_desc': 'Günlük, haftalık ve aylık istatistikler',
      'daily_notes_feature': 'Günlük Notlar',
      'daily_notes_desc': 'Ruh halin ve deneyimlerini kaydet',
      'reminders': 'Hatırlatmalar',
      'reminders_desc': 'Belirlediğin saatlerde bildirim al',
      'categories_feature': 'Kategoriler',
      'categories_desc': 'Manevi, eğitim, sağlık ve kişisel gelişim',
      'detailed_analysis': 'Detaylı Analiz',
      'analysis_desc': 'Grafikler ve başarı oranları',
      'copyright_title': 'Telif Hakları',
      'copyright_desc': '© 2024 Motiv App. Tüm hakları saklıdır. Bu uygulamanın tüm içeriği, tasarımı ve kodları telif hakkı ile korunmaktadır.',
      'privacy_title': 'Gizlilik',
      'privacy_desc': 'Kişisel verileriniz güvenli bir şekilde saklanır ve üçüncü taraflarla paylaşılmaz. Verileriniz sadece uygulama işlevsellik için kullanılır.',
      'terms_title': 'Kullanım Koşulları',
      'terms_desc': 'Bu uygulamayı kullanarak, belirlenen kullanım koşullarını kabul etmiş olursunuz. Uygulamayı kötüye kullanmak yasaktır.',
      'disclaimer_title': 'Sorumluluk Reddi',
      'disclaimer_desc': 'Uygulama "olduğu gibi" sunulmaktadır. Geliştiriciler, uygulamanın kullanımından doğabilecek herhangi bir zarardan sorumlu değildir.',
      'email': 'E-posta',
      'website': 'Web Sitesi',
      'bug_report': 'Hata Bildirimi',
      'bug_report_desc': 'Bir hata mı buldun? Bize bildir!',
      'rating': 'Değerlendirme',
      'rating_desc': 'Uygulamayı beğendiysen yıldız ver!',
      'feedback_message': 'Geri bildirimleriniz bizim için çok değerli. Uygulamayı geliştirmek için önerilerinizi bekliyoruz.',
      'alarm_time': 'Alarm Saati',
      'daily_tasks': 'Günlük Görevler',
      'no_daily_tasks': 'Henüz günlük görev eklemedin',
      'add_first_task': 'İlk görevini eklemek için + butonuna bas',
      'active_tasks': 'Aktif Görevler',
      'completed_tasks': 'Tamamlanan Görevler',
      'expires': 'Süresi Doluyor',
      'expired': 'Süresi Doldu',
      'mark_complete': 'Tamamlandı Olarak İşaretle',
      'task_completed': 'Görev Tamamlandı',
      'add_to_calendar_question': 'Bu görevi takvime eklemek istiyor musun?',
      'yes': 'Evet',
      'no': 'Hayır',
      'added_to_calendar': 'Takvime eklendi!',
      'task_deleted': 'Görev silindi',
      'add_daily_task': 'Günlük Görev Ekle',
      'task_title': 'Görev Başlığı',
      'expires_in': 'Süresi',
      'hours': 'saat',
      'completed_motivations_today': 'Bugün tamamlanan motivasyonlar:',
      'remaining_motivations_today': 'Bugün kalan motivasyonlar:',
      'target': 'Hedef',
      'more': 'tane daha',
      'no_motivations_added_yet': 'Henüz motivasyon eklenmemiş',
      'tasks_in_progress': 'Şu anda devam eden görevler',
      'completed_tasks_today': 'Bugün tamamlanan görevler',
      'expired_tasks': 'Süresi geçmiş görevler',
      'no_tasks_in_category': 'Bu kategoride görev bulunamadı',
      'tasks': 'görev',
      'task': 'görev',
      'active': 'Aktif',
      'close': 'Kapat',
      'created': 'Oluşturuldu',
      'note': 'Not',
      'add_note_hint': 'Notunuzu buraya yazın...',
      'note_added': 'Not eklendi',
      'complete_task': 'Görevi Tamamla',
      'mark_task_complete_question': 'Bu görevi tamamlandı olarak işaretlemek istiyor musun?',
      'error_occurred': 'Bir hata oluştu',
      'progress_chart': 'İlerleme Grafiği',
      'details': 'Detayları',
      'motivation_notes_hint': 'Bu motivasyon hakkında notların...',
      'yes_did_it': 'Evet, Yaptım',
      'no_could_not': 'Hayır, Yapamadım',
      'example': 'Örnek',
      'how_do_you_feel_today': 'Bu motivasyon için bugün ruh halin nasıl?',
      'complete_record': 'Kaydı Tamamla',
      'daily_record_completed': 'için günlük kayıt tamamlandı!',
      'record_saved_try_tomorrow': 'Kayıt alındı. Yarın tekrar dene!',
      'mood_bad': 'Kötü',
      'mood_difficult': 'Zor',
      'mood_normal': 'Normal',
      'mood_good': 'İyi',
      'mood_great': 'Harika',
      'password': 'Şifre',
      'email_required': 'E-posta gerekli',
      'email_invalid': 'Geçersiz e-posta',
      'password_required': 'Şifre gerekli',
      'password_min_length': 'Şifre en az 6 karakter olmalı',
      'remember_me': 'Beni Hatırla',
      'sign_up': 'Kayıt Ol',
      'sign_in': 'Giriş Yap',
      'already_have_account': 'Zaten hesabın var mı? Giriş yap',
      'dont_have_account': 'Hesabın yok mu? Kayıt ol',
      'or': 'veya',
      'check_email_verification': 'E-postanı kontrol et ve doğrulama linkine tıkla',
      'account': 'Hesap',
      'profile_info': 'Profil Bilgileri',
      'full_name': 'Ad Soyad',
      'age': 'Yaş',
      'location': 'Yaşadığı Yer',
      'no_name': 'Ad Girilmemiş',
      'name_required': 'Ad soyad gerekli',
      'age_invalid': 'Geçersiz yaş (1-120 arası)',
      'profile_updated': 'Profil güncellendi',
      'sign_out': 'Çıkış Yap',
      'sign_out_confirm': 'Hesaptan çıkış yapmak istediğinizden emin misiniz?'
    },
    'en': {
      'app_name': 'Motiv App',
      'app_subtitle': 'Track Your Motivation',
      'welcome_morning': 'Good Morning!',
      'welcome_afternoon': 'Good Afternoon!',
      'welcome_evening': 'Good Evening!',
      'welcome_message': 'Which goals will you achieve today?',
      'today_summary': 'Today\'s Summary',
      'this_week': 'This Week',
      'completed': 'Completed',
      'remaining': 'Remaining',

      'my_motivations': 'My Motivations',
      'quick_actions': 'Quick Actions',
      'complete_today': 'Complete Today',
      'dashboard': 'Home',
      'motivations': 'Motivations',
      'motivation': 'Motivation',
      'about': 'About',
      'daily_record': 'Daily Record',
      'view_details': 'View Details',
      'statistics_progress': 'Statistics and progress charts',
      'did_you_do_today': 'Did you accomplish this motivation today?',
      'language': 'Language',
      'turkish': 'Türkçe',
      'english': 'English',
      'days': 'days',
      'minutes': 'min',
      'total_days': 'Total Days',
      'total_time': 'Total Time',

      'add_motivation': 'Add Motivation',
      'no_motivations': 'No motivations added yet',
      'add_first_motivation': 'Tap + button to add your first motivation',
      'login_welcome': 'Welcome to Motiv App',
      'login_subtitle': 'Start tracking your motivation',
      'google_signin': 'Sign in with Google',
      'continue_guest': 'Continue as guest',
      'completed_routines': 'Completed Routines',
      'no_completed_routines': 'No completed routines yet',
      'completed_routines_desc': 'When your motivations become routine\nthey will appear here',
      'routine_completed': 'Became Routine',
      'predefined_motivations': 'Ready Motivations',
      'custom_motivation': 'Create Custom Motivation',
      'motivation_title': 'Motivation Title',
      'description': 'Description',
      'category': 'Category',
      'frequency': 'Frequency',
      'target_time': 'Target Time (minutes)',
      'reminder': 'Reminder',
      'set_alarm': 'Set Alarm',
      'alarm_desc': 'Get reminder at your set time',
      'select_alarm_time': 'Select Alarm Time',
      'notes_optional': 'Notes (Optional)',
      'save_motivation': 'Save Motivation',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'spiritual': 'Spiritual',
      'education': 'Education',
      'health': 'Health',
      'personal': 'Personal',
      'title_required': 'Title is required',
      'select_day': 'Please select at least one day',
      'which_days': 'Which Days?',
      'type_selection': 'Type Selection',
      'how_often': 'How Often?',
      'target_time_minutes': 'Target time is required',
      'app_info': 'App Information',
      'version': 'Version 1.0.0',
      'app_description': 'Track your motivation, reach your goals! Create and maintain your daily habits.',
      'features': 'Features',
      'legal_info': 'Legal Information',
      'contact': 'Contact',
      'copyright': 'Copyright',
      'privacy': 'Privacy',
      'terms': 'Terms of Use',
      'disclaimer': 'Disclaimer',
      'all': 'All',
      'no_motivations_found': 'No motivations found',
      'household': 'Household',
      'self_care': 'Self Care',
      'social': 'Social',
      'hobby': 'Hobby',
      'career': 'Career',
      'completed_days': 'Completed',
      'current_streak': 'Streak',
      'success_rate': 'Success Rate',
      'last_30_days': 'Last 30 Days',
      'daily_notes': 'Daily Notes',
      'add_note': 'Add Note',
      'no_notes_yet': 'No notes added yet. Tap + button to add your first note.',
      'recent_activities': 'Recent Activities',
      'add_daily_note': 'Add Daily Note',
      'how_was_today': 'How was today? Write your notes...',
      'how_do_you_feel': 'How do you feel?',
      'cancel': 'Cancel',
      'save': 'Save',
      'note_saved': 'Note saved!',
      'complete_today_title': 'Complete Today',
      'did_you_complete': 'Did you complete this motivation today?',
      'how_many_minutes': 'How many minutes did you spend?',
      'complete': 'Complete',
      'marked_complete': 'Marked as completed for today!',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'completed_status': 'Completed',
      'not_completed': 'Not Completed',
      'not_completed_status': 'Not Completed',
      'ok': 'OK',
      'delete': 'Delete',
      'motivation_moved_to_completed': 'Motivation moved to completed routines!',
      'motivation_deleted': 'Motivation deleted',
      'view': 'View',
      'mark_all_complete_question': 'Do you want to mark all motivations as completed for today?',
      'all_motivations_completed': 'All motivations completed!',
      'create_daily_record': 'Create Daily Record',
      'dashboard_feature': 'Dashboard',
      'dashboard_desc': 'View summary of your motivations',
      'progress_tracking': 'Progress Tracking',
      'progress_desc': 'Daily, weekly and monthly statistics',
      'daily_notes_feature': 'Daily Notes',
      'daily_notes_desc': 'Record your mood and experiences',
      'reminders': 'Reminders',
      'reminders_desc': 'Get notifications at your set times',
      'categories_feature': 'Categories',
      'categories_desc': 'Spiritual, education, health and personal development',
      'detailed_analysis': 'Detailed Analysis',
      'analysis_desc': 'Charts and success rates',
      'copyright_title': 'Copyright',
      'copyright_desc': '© 2024 Motiv App. All rights reserved. All content, design and code of this application are protected by copyright.',
      'privacy_title': 'Privacy',
      'privacy_desc': 'Your personal data is stored securely and not shared with third parties. Your data is only used for app functionality.',
      'terms_title': 'Terms of Use',
      'terms_desc': 'By using this application, you agree to the specified terms of use. Misuse of the application is prohibited.',
      'disclaimer_title': 'Disclaimer',
      'disclaimer_desc': 'The application is provided "as is". Developers are not responsible for any damage that may arise from the use of the application.',
      'email': 'Email',
      'website': 'Website',
      'bug_report': 'Bug Report',
      'bug_report_desc': 'Found a bug? Let us know!',
      'rating': 'Rating',
      'rating_desc': 'If you liked the app, give us stars!',
      'feedback_message': 'Your feedback is very valuable to us. We look forward to your suggestions to improve the app.',
      'alarm_time': 'Alarm Time',
      'daily_tasks': 'Daily Tasks',
      'no_daily_tasks': 'No daily tasks added yet',
      'add_first_task': 'Tap + button to add your first task',
      'active_tasks': 'Active Tasks',
      'completed_tasks': 'Completed Tasks',
      'expires': 'Expires',
      'expired': 'Expired',
      'mark_complete': 'Mark as Complete',
      'task_completed': 'Task Completed',
      'add_to_calendar_question': 'Do you want to add this task to calendar?',
      'yes': 'Yes',
      'no': 'No',
      'added_to_calendar': 'Added to calendar!',
      'task_deleted': 'Task deleted',
      'add_daily_task': 'Add Daily Task',
      'task_title': 'Task Title',
      'expires_in': 'Expires in',
      'hours': 'hours',
      'completed_motivations_today': 'Completed motivations today:',
      'remaining_motivations_today': 'Remaining motivations today:',
      'target': 'Target',
      'more': 'more',
      'no_motivations_added_yet': 'No motivations added yet',
      'tasks_in_progress': 'Tasks currently in progress',
      'completed_tasks_today': 'Tasks completed today',
      'expired_tasks': 'Expired tasks',
      'no_tasks_in_category': 'No tasks found in this category',
      'tasks': 'tasks',
      'task': 'task',
      'active': 'Active',
      'close': 'Close',
      'created': 'Created',
      'note': 'Note',
      'add_note_hint': 'Write your note here...',
      'note_added': 'Note added',
      'complete_task': 'Complete Task',
      'mark_task_complete_question': 'Do you want to mark this task as completed?',
      'error_occurred': 'An error occurred',
      'progress_chart': 'Progress Chart',
      'details': 'Details',
      'motivation_notes_hint': 'Your notes about this motivation...',
      'yes_did_it': 'Yes, I Did It',
      'no_could_not': 'No, I Could Not',
      'example': 'Example',
      'how_do_you_feel_today': 'How do you feel about this motivation today?',
      'complete_record': 'Complete Record',
      'daily_record_completed': 'daily record completed!',
      'record_saved_try_tomorrow': 'Record saved. Try again tomorrow!',
      'mood_bad': 'Bad',
      'mood_difficult': 'Difficult',
      'mood_normal': 'Normal',
      'mood_good': 'Good',
      'mood_great': 'Great',
      'password': 'Password',
      'email_required': 'Email is required',
      'email_invalid': 'Invalid email',
      'password_required': 'Password is required',
      'password_min_length': 'Password must be at least 6 characters',
      'remember_me': 'Remember Me',
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'already_have_account': 'Already have an account? Sign in',
      'dont_have_account': 'Don\'t have an account? Sign up',
      'or': 'or',
      'check_email_verification': 'Check your email and click the verification link',
      'account': 'Account',
      'profile_info': 'Profile Information',
      'full_name': 'Full Name',
      'age': 'Age',
      'location': 'Location',
      'no_name': 'No Name Entered',
      'name_required': 'Full name is required',
      'age_invalid': 'Invalid age (1-120)',
      'profile_updated': 'Profile updated',
      'sign_out': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?'
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}